### ISSUE TITLE
Sitemap Recognized as HTML by Webmaster Tools

### ISSUE THREAD

**Issue by steveafrost** [Aupajo/middleman-search_engine_sitemap#9]
Hey there - first, thanks for making this gem for middleman. Upon submitting the sitemap to Google Webmaster Tools, it complains that it is in an HTML format when it obviously isn't and is accessible at /sitemap.xml. Is this a new issue?

<img width="824" alt="screen shot 2017-03-14 at 10 16 16 pm" src="https://cloud.githubusercontent.com/assets/4761639/23930628/e92cf266-0903-11e7-82c9-117583bcd5c3.png">

**Comment by Aupajo** [comment]
@steveafrost That's a new one on me! Can you send me a link/gist to your `/sitemap.xml`?

**Comment by steveafrost** [comment]
Ah, it was an error on my end. The DNS had a duplicate IP which was hitting a parking page and was what Google was picking up on when I submitted the map. Closing this issue.

**Comment by Aupajo** [comment]
@steveafrost No worries! Glad you resolved the issue.
